name: docker
on:
 push:
  tags:
   - v*

jobs:
  push_to_registry:
    name: Push docker image to dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v2
      - name: push to dockerhub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: royfrancis/pophelpershiny
          tag_with_ref: true
